#!/bin/sh

# TODO edit /usr/lib/draw.io/src/main/electron.js
# let argv = process.argv;
# argv = argv.filter(i => !i.startsWith('--enable-features=') && !i.startsWith('--ozone-platform='));

if [ -n "$WAYLAND_DISPLAY" ]; then
    args="--enable-features=UseOzonePlatform --ozone-platform=wayland"
else
    args=""
fi

exec ~/.local/opt/drawio.AppImage $args "$@"
