#!/bin/sh

# TODO edit /usr/lib/draw.io/src/main/electron.js
# let argv = process.argv;
# argv = argv.filter(i => !i.startsWith('--enable-features=') && !i.startsWith('--ozone-platform='));

exec electron25 \
    $([ -n "$WAYLAND_DISPLAY" ] && \
      echo "--enable-features=UseOzonePlatform --ozone-platform=wayland") \
    /usr/lib/draw.io "$@"
