#!/bin/sh

sxhkd -c ~/.config/bspwm/sxhkdrc &
~/.config/polybar/launch.sh &

bspc monitor primary -d 1 2 3 4 term
[ $(xrandr --listactivemonitors | wc -l) -gt 2 ] && \
    bspc monitor primary#next -d a s d f

bspc config border_width             4
bspc config window_gap               0
bspc config focus_follows_pointer    true
bspc config pointer_follows_monitor  true
bspc config split_ratio              0.52
bspc config borderless_monocle       true
bspc config gapless_monocle          true

bspc rule -a *:tmux_term desktop=term

