#!/bin/sh

mod=Mod4

# riverctl map normal None F12 spawn ~/.config/river/terminal.sh
# riverctl map normal None Print spawn spectacle

riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view

riverctl map normal $mod Return spawn alacritty
riverctl map normal $mod Space spawn 'wofi --show drun --allow-images --allow-markup --gtk-dark'

riverctl map normal $mod+Shift E exit
riverctl map normal $mod+Shift Q close

riverctl map normal $mod+Shift Return toggle-fullscreen
riverctl map normal $mod+Shift Space toggle-float

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))
    riverctl map normal $mod $i set-focused-tags $tags
    riverctl map normal $mod+Shift $i set-view-tags $tags
done

riverctl focus-follows-cursor normal
riverctl set-cursor-wrap on-output-change
riverctl xcursor-theme default 32

riverctl default-layout rivertile

# export GDK_DPI_SCALE=0.95
gsettings set org.gnome.desktop.interface scaling-factor 1
gsettings set org.gnome.desktop.interface text-scaling-factor 1
gsettings set org.gnome.desktop.interface cursor-size 32

export QT_QPA_PLATFORM=wayland
systemctl --user import-environment \
    QT_QPA_PLATFORM \
    WAYLAND_DISPLAY \
    XDG_SESSION_TYPE
dbus-update-activation-environment --systemd --all

systemctl --user restart plasma-kactivitymanagerd.service

exec rivertile
