#!/bin/sh

mod=Mod4

# displays="$(wlr-randr | grep -e '^[[:alnum:]]' | cut -d ' ' -f 1)"
# primary=eDP-1

# riverctl map normal None F12 spawn ~/.config/river/terminal.sh
# riverctl map normal None Print spawn spectacle

riverctl map-pointer normal $mod BTN_LEFT move-view
riverctl map-pointer normal $mod BTN_RIGHT resize-view

riverctl map normal $mod Return spawn alacritty
riverctl map normal $mod Space spawn ~/.dotfiles/wofi/run.sh

riverctl map normal $mod+Shift E exit
riverctl map normal $mod+Shift Q close

riverctl map normal $mod+Shift Return toggle-fullscreen
riverctl map normal $mod+Shift Space toggle-float

riverctl map normal $mod h focus-view left
riverctl map normal $mod j focus-view down
riverctl map normal $mod k focus-view up
riverctl map normal $mod l focus-view right

riverctl map normal $mod+Shift H swap left
riverctl map normal $mod+Shift J swap down
riverctl map normal $mod+Shift K swap up
riverctl map normal $mod+Shift L swap right

for i in 1:1 2:2 3:3 4:4 5:a 6:s 7:d 8:f; do
    index=${i%:*}
    key=${i#*:}
    tags=$((1 << ($index - 1)))
    riverctl map normal $mod $key set-focused-tags $tags
    riverctl map normal $mod+Shift $key set-view-tags $tags
done

riverctl focus-follows-cursor normal
riverctl set-cursor-wrap on-output-change
riverctl xcursor-theme default 32

riverctl default-layout rivertile

# export GDK_DPI_SCALE=0.95
if command -v gsettings > /dev/null; then
    gsettings set org.gnome.desktop.interface scaling-factor 1
    gsettings set org.gnome.desktop.interface text-scaling-factor 1
    gsettings set org.gnome.desktop.interface cursor-size 32
fi

export QT_QPA_PLATFORM=wayland
export XDG_CURRENT_DESKTOP=river

if command -v systemctl > /dev/null; then
    systemctl --user import-environment \
        QT_QPA_PLATFORM \
        SWAYSOCK \
        WAYLAND_DISPLAY \
        XDG_SESSION_TYPE \
        XDG_CURRENT_DESKTOP
    dbus-update-activation-environment --systemd --all

    systemctl --user restart xdg-desktop-portal
    systemctl --user restart xdg-desktop-portal-wlr
    systemctl --user restart plasma-kactivitymanagerd
fi

waybar -c ~/.config/waybar/river.conf &

exec rivertile
